; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv64_cheri_uninit_llc -verify-machineinstrs -o - %s | FileCheck %s
; Regression test for a crash found while compiling functions with frames greater than 2048 bytes
; after the April 2021 upstream LLVM merge (caused by a mismerge of 02ffbac844e01df2c95dfcb3117213211fe2226d).
; Assertion failed: (RealDef != nullptr && "Must have at least 1 Def"), function scavengeVReg

%struct.large = type { [1024 x i8] }
%struct.too.large = type { [2048 x i8] }

declare i32 @use_i128(i128 addrspace(200)*)
declare i32 @use_large(%struct.large addrspace(200)*)
declare i32 @use_too_large(%struct.too.large addrspace(200)*)

define void @frame_locals_below_threshold(i128 addrspace(200)*%arg1, i128 addrspace(200)*%arg2, i128 addrspace(200)*%arg3, i128 addrspace(200)*%arg4, i128 addrspace(200)*%arg5, i128 addrspace(200)*%arg6, i128 addrspace(200)*%arg7, i128 addrspace(200)*%arg8, i128 addrspace(200)*%arg9) local_unnamed_addr addrspace(200) nounwind {
; CHECK-LABEL: frame_locals_below_threshold:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    csc cra, 1056(csp) # 16-byte Folded Spill
; CHECK-NEXT:    cincoffset ca0, csp, 1040
; CHECK-NEXT:    csetbounds ca0, ca0, 16
; CHECK-NEXT:    ccall use_i128
; CHECK-NEXT:    cincoffset ca0, csp, 16
; CHECK-NEXT:    csetbounds ca0, ca0, 1024
; CHECK-NEXT:    ccall use_large
; CHECK-NEXT:    clc cra, 1056(csp) # 16-byte Folded Reload
; CHECK-NEXT:    csc cnull, 0(csp)
; CHECK-NEXT:    csc cnull, 16(csp)
; CHECK-NEXT:    csc cnull, 32(csp)
; CHECK-NEXT:    csc cnull, 48(csp)
; CHECK-NEXT:    csc cnull, 64(csp)
; CHECK-NEXT:    csc cnull, 80(csp)
; CHECK-NEXT:    csc cnull, 96(csp)
; CHECK-NEXT:    csc cnull, 112(csp)
; CHECK-NEXT:    csc cnull, 128(csp)
; CHECK-NEXT:    csc cnull, 144(csp)
; CHECK-NEXT:    csc cnull, 160(csp)
; CHECK-NEXT:    csc cnull, 176(csp)
; CHECK-NEXT:    csc cnull, 192(csp)
; CHECK-NEXT:    csc cnull, 208(csp)
; CHECK-NEXT:    csc cnull, 224(csp)
; CHECK-NEXT:    csc cnull, 240(csp)
; CHECK-NEXT:    csc cnull, 256(csp)
; CHECK-NEXT:    csc cnull, 272(csp)
; CHECK-NEXT:    csc cnull, 288(csp)
; CHECK-NEXT:    csc cnull, 304(csp)
; CHECK-NEXT:    csc cnull, 320(csp)
; CHECK-NEXT:    csc cnull, 336(csp)
; CHECK-NEXT:    csc cnull, 352(csp)
; CHECK-NEXT:    csc cnull, 368(csp)
; CHECK-NEXT:    csc cnull, 384(csp)
; CHECK-NEXT:    csc cnull, 400(csp)
; CHECK-NEXT:    csc cnull, 416(csp)
; CHECK-NEXT:    csc cnull, 432(csp)
; CHECK-NEXT:    csc cnull, 448(csp)
; CHECK-NEXT:    csc cnull, 464(csp)
; CHECK-NEXT:    csc cnull, 480(csp)
; CHECK-NEXT:    csc cnull, 496(csp)
; CHECK-NEXT:    csc cnull, 512(csp)
; CHECK-NEXT:    csc cnull, 528(csp)
; CHECK-NEXT:    csc cnull, 544(csp)
; CHECK-NEXT:    csc cnull, 560(csp)
; CHECK-NEXT:    csc cnull, 576(csp)
; CHECK-NEXT:    csc cnull, 592(csp)
; CHECK-NEXT:    csc cnull, 608(csp)
; CHECK-NEXT:    csc cnull, 624(csp)
; CHECK-NEXT:    csc cnull, 640(csp)
; CHECK-NEXT:    csc cnull, 656(csp)
; CHECK-NEXT:    csc cnull, 672(csp)
; CHECK-NEXT:    csc cnull, 688(csp)
; CHECK-NEXT:    csc cnull, 704(csp)
; CHECK-NEXT:    csc cnull, 720(csp)
; CHECK-NEXT:    csc cnull, 736(csp)
; CHECK-NEXT:    csc cnull, 752(csp)
; CHECK-NEXT:    csc cnull, 768(csp)
; CHECK-NEXT:    csc cnull, 784(csp)
; CHECK-NEXT:    csc cnull, 800(csp)
; CHECK-NEXT:    csc cnull, 816(csp)
; CHECK-NEXT:    csc cnull, 832(csp)
; CHECK-NEXT:    csc cnull, 848(csp)
; CHECK-NEXT:    csc cnull, 864(csp)
; CHECK-NEXT:    csc cnull, 880(csp)
; CHECK-NEXT:    csc cnull, 896(csp)
; CHECK-NEXT:    csc cnull, 912(csp)
; CHECK-NEXT:    csc cnull, 928(csp)
; CHECK-NEXT:    csc cnull, 944(csp)
; CHECK-NEXT:    csc cnull, 960(csp)
; CHECK-NEXT:    csc cnull, 976(csp)
; CHECK-NEXT:    csc cnull, 992(csp)
; CHECK-NEXT:    csc cnull, 1008(csp)
; CHECK-NEXT:    csc cnull, 1024(csp)
; CHECK-NEXT:    csc cnull, 1040(csp)
; CHECK-NEXT:    csc cnull, 1056(csp)
; CHECK-NEXT:    cincoffset csp, csp, 1072
; CHECK-NEXT:    cret
entry:
  %obj1 = alloca i128, align 16, addrspace(200)
  %obj2 = alloca %struct.large, align 1, addrspace(200)
  call i32 @use_i128(i128 addrspace(200)* %obj1)
  call i32 @use_large(%struct.large addrspace(200)* %obj2)
  ret void
}

define void @locals_below_frame_above_threshold(i128 addrspace(200)*%arg1, i128 addrspace(200)*%arg2, i128 addrspace(200)*%arg3, i128 addrspace(200)*%arg4, i128 addrspace(200)*%arg5, i128 addrspace(200)*%arg6, i128 addrspace(200)*%arg7, i128 addrspace(200)*%arg8, i128 addrspace(200)*%arg9, i128 addrspace(200)*%arg10, i128 addrspace(200)*%arg11) local_unnamed_addr addrspace(200) nounwind {
; CHECK-LABEL: locals_below_frame_above_threshold:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    csc cra, 1056(csp) # 16-byte Folded Spill
; CHECK-NEXT:    cincoffset ca0, csp, 1040
; CHECK-NEXT:    csetbounds ca0, ca0, 16
; CHECK-NEXT:    ccall use_i128
; CHECK-NEXT:    cincoffset ca0, csp, 16
; CHECK-NEXT:    csetbounds ca0, ca0, 1024
; CHECK-NEXT:    ccall use_large
; CHECK-NEXT:    clc cra, 1056(csp) # 16-byte Folded Reload
; CHECK-NEXT:    csc cnull, 0(csp)
; CHECK-NEXT:    csc cnull, 16(csp)
; CHECK-NEXT:    csc cnull, 32(csp)
; CHECK-NEXT:    csc cnull, 48(csp)
; CHECK-NEXT:    csc cnull, 64(csp)
; CHECK-NEXT:    csc cnull, 80(csp)
; CHECK-NEXT:    csc cnull, 96(csp)
; CHECK-NEXT:    csc cnull, 112(csp)
; CHECK-NEXT:    csc cnull, 128(csp)
; CHECK-NEXT:    csc cnull, 144(csp)
; CHECK-NEXT:    csc cnull, 160(csp)
; CHECK-NEXT:    csc cnull, 176(csp)
; CHECK-NEXT:    csc cnull, 192(csp)
; CHECK-NEXT:    csc cnull, 208(csp)
; CHECK-NEXT:    csc cnull, 224(csp)
; CHECK-NEXT:    csc cnull, 240(csp)
; CHECK-NEXT:    csc cnull, 256(csp)
; CHECK-NEXT:    csc cnull, 272(csp)
; CHECK-NEXT:    csc cnull, 288(csp)
; CHECK-NEXT:    csc cnull, 304(csp)
; CHECK-NEXT:    csc cnull, 320(csp)
; CHECK-NEXT:    csc cnull, 336(csp)
; CHECK-NEXT:    csc cnull, 352(csp)
; CHECK-NEXT:    csc cnull, 368(csp)
; CHECK-NEXT:    csc cnull, 384(csp)
; CHECK-NEXT:    csc cnull, 400(csp)
; CHECK-NEXT:    csc cnull, 416(csp)
; CHECK-NEXT:    csc cnull, 432(csp)
; CHECK-NEXT:    csc cnull, 448(csp)
; CHECK-NEXT:    csc cnull, 464(csp)
; CHECK-NEXT:    csc cnull, 480(csp)
; CHECK-NEXT:    csc cnull, 496(csp)
; CHECK-NEXT:    csc cnull, 512(csp)
; CHECK-NEXT:    csc cnull, 528(csp)
; CHECK-NEXT:    csc cnull, 544(csp)
; CHECK-NEXT:    csc cnull, 560(csp)
; CHECK-NEXT:    csc cnull, 576(csp)
; CHECK-NEXT:    csc cnull, 592(csp)
; CHECK-NEXT:    csc cnull, 608(csp)
; CHECK-NEXT:    csc cnull, 624(csp)
; CHECK-NEXT:    csc cnull, 640(csp)
; CHECK-NEXT:    csc cnull, 656(csp)
; CHECK-NEXT:    csc cnull, 672(csp)
; CHECK-NEXT:    csc cnull, 688(csp)
; CHECK-NEXT:    csc cnull, 704(csp)
; CHECK-NEXT:    csc cnull, 720(csp)
; CHECK-NEXT:    csc cnull, 736(csp)
; CHECK-NEXT:    csc cnull, 752(csp)
; CHECK-NEXT:    csc cnull, 768(csp)
; CHECK-NEXT:    csc cnull, 784(csp)
; CHECK-NEXT:    csc cnull, 800(csp)
; CHECK-NEXT:    csc cnull, 816(csp)
; CHECK-NEXT:    csc cnull, 832(csp)
; CHECK-NEXT:    csc cnull, 848(csp)
; CHECK-NEXT:    csc cnull, 864(csp)
; CHECK-NEXT:    csc cnull, 880(csp)
; CHECK-NEXT:    csc cnull, 896(csp)
; CHECK-NEXT:    csc cnull, 912(csp)
; CHECK-NEXT:    csc cnull, 928(csp)
; CHECK-NEXT:    csc cnull, 944(csp)
; CHECK-NEXT:    csc cnull, 960(csp)
; CHECK-NEXT:    csc cnull, 976(csp)
; CHECK-NEXT:    csc cnull, 992(csp)
; CHECK-NEXT:    csc cnull, 1008(csp)
; CHECK-NEXT:    csc cnull, 1024(csp)
; CHECK-NEXT:    csc cnull, 1040(csp)
; CHECK-NEXT:    csc cnull, 1056(csp)
; CHECK-NEXT:    cincoffset csp, csp, 1072
; CHECK-NEXT:    cret
entry:
  %obj1 = alloca i128, align 16, addrspace(200)
  %obj2 = alloca %struct.large, align 1, addrspace(200)
  call i32 @use_i128(i128 addrspace(200)* %obj1)
  call i32 @use_large(%struct.large addrspace(200)* %obj2)
  ret void
}

define void @frame_locals_above_threshold(i128 addrspace(200)*%arg1, i128 addrspace(200)*%arg2, i128 addrspace(200)*%arg3, i128 addrspace(200)*%arg4, i128 addrspace(200)*%arg5, i128 addrspace(200)*%arg6, i128 addrspace(200)*%arg7, i128 addrspace(200)*%arg8, i128 addrspace(200)*%arg9, i128 addrspace(200)*%arg10, i128 addrspace(200)*%arg11) local_unnamed_addr addrspace(200) nounwind {
; CHECK-LABEL: frame_locals_above_threshold:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    csc cra, 2016(csp) # 16-byte Folded Spill
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    usc csp, cnull, csp
; CHECK-NEXT:    lui a0, 1
; CHECK-NEXT:    addiw a0, a0, -2032
; CHECK-NEXT:    cincoffset ca0, csp, a0
; CHECK-NEXT:    csetbounds ca0, ca0, 16
; CHECK-NEXT:    ccall use_i128
; CHECK-NEXT:    cincoffset ca0, csp, 16
; CHECK-NEXT:    csetbounds ca0, ca0, 2048
; CHECK-NEXT:    ccall use_too_large
; CHECK-NEXT:    csc cnull, 0(csp)
; CHECK-NEXT:    csc cnull, 16(csp)
; CHECK-NEXT:    csc cnull, 32(csp)
; CHECK-NEXT:    csc cnull, 48(csp)
; CHECK-NEXT:    cincoffset csp, csp, 64
; CHECK-NEXT:    clc cra, 2016(csp) # 16-byte Folded Reload
; CHECK-NEXT:    csc cnull, 0(csp)
; CHECK-NEXT:    csc cnull, 16(csp)
; CHECK-NEXT:    csc cnull, 32(csp)
; CHECK-NEXT:    csc cnull, 48(csp)
; CHECK-NEXT:    csc cnull, 64(csp)
; CHECK-NEXT:    csc cnull, 80(csp)
; CHECK-NEXT:    csc cnull, 96(csp)
; CHECK-NEXT:    csc cnull, 112(csp)
; CHECK-NEXT:    csc cnull, 128(csp)
; CHECK-NEXT:    csc cnull, 144(csp)
; CHECK-NEXT:    csc cnull, 160(csp)
; CHECK-NEXT:    csc cnull, 176(csp)
; CHECK-NEXT:    csc cnull, 192(csp)
; CHECK-NEXT:    csc cnull, 208(csp)
; CHECK-NEXT:    csc cnull, 224(csp)
; CHECK-NEXT:    csc cnull, 240(csp)
; CHECK-NEXT:    csc cnull, 256(csp)
; CHECK-NEXT:    csc cnull, 272(csp)
; CHECK-NEXT:    csc cnull, 288(csp)
; CHECK-NEXT:    csc cnull, 304(csp)
; CHECK-NEXT:    csc cnull, 320(csp)
; CHECK-NEXT:    csc cnull, 336(csp)
; CHECK-NEXT:    csc cnull, 352(csp)
; CHECK-NEXT:    csc cnull, 368(csp)
; CHECK-NEXT:    csc cnull, 384(csp)
; CHECK-NEXT:    csc cnull, 400(csp)
; CHECK-NEXT:    csc cnull, 416(csp)
; CHECK-NEXT:    csc cnull, 432(csp)
; CHECK-NEXT:    csc cnull, 448(csp)
; CHECK-NEXT:    csc cnull, 464(csp)
; CHECK-NEXT:    csc cnull, 480(csp)
; CHECK-NEXT:    csc cnull, 496(csp)
; CHECK-NEXT:    csc cnull, 512(csp)
; CHECK-NEXT:    csc cnull, 528(csp)
; CHECK-NEXT:    csc cnull, 544(csp)
; CHECK-NEXT:    csc cnull, 560(csp)
; CHECK-NEXT:    csc cnull, 576(csp)
; CHECK-NEXT:    csc cnull, 592(csp)
; CHECK-NEXT:    csc cnull, 608(csp)
; CHECK-NEXT:    csc cnull, 624(csp)
; CHECK-NEXT:    csc cnull, 640(csp)
; CHECK-NEXT:    csc cnull, 656(csp)
; CHECK-NEXT:    csc cnull, 672(csp)
; CHECK-NEXT:    csc cnull, 688(csp)
; CHECK-NEXT:    csc cnull, 704(csp)
; CHECK-NEXT:    csc cnull, 720(csp)
; CHECK-NEXT:    csc cnull, 736(csp)
; CHECK-NEXT:    csc cnull, 752(csp)
; CHECK-NEXT:    csc cnull, 768(csp)
; CHECK-NEXT:    csc cnull, 784(csp)
; CHECK-NEXT:    csc cnull, 800(csp)
; CHECK-NEXT:    csc cnull, 816(csp)
; CHECK-NEXT:    csc cnull, 832(csp)
; CHECK-NEXT:    csc cnull, 848(csp)
; CHECK-NEXT:    csc cnull, 864(csp)
; CHECK-NEXT:    csc cnull, 880(csp)
; CHECK-NEXT:    csc cnull, 896(csp)
; CHECK-NEXT:    csc cnull, 912(csp)
; CHECK-NEXT:    csc cnull, 928(csp)
; CHECK-NEXT:    csc cnull, 944(csp)
; CHECK-NEXT:    csc cnull, 960(csp)
; CHECK-NEXT:    csc cnull, 976(csp)
; CHECK-NEXT:    csc cnull, 992(csp)
; CHECK-NEXT:    csc cnull, 1008(csp)
; CHECK-NEXT:    csc cnull, 1024(csp)
; CHECK-NEXT:    csc cnull, 1040(csp)
; CHECK-NEXT:    csc cnull, 1056(csp)
; CHECK-NEXT:    csc cnull, 1072(csp)
; CHECK-NEXT:    csc cnull, 1088(csp)
; CHECK-NEXT:    csc cnull, 1104(csp)
; CHECK-NEXT:    csc cnull, 1120(csp)
; CHECK-NEXT:    csc cnull, 1136(csp)
; CHECK-NEXT:    csc cnull, 1152(csp)
; CHECK-NEXT:    csc cnull, 1168(csp)
; CHECK-NEXT:    csc cnull, 1184(csp)
; CHECK-NEXT:    csc cnull, 1200(csp)
; CHECK-NEXT:    csc cnull, 1216(csp)
; CHECK-NEXT:    csc cnull, 1232(csp)
; CHECK-NEXT:    csc cnull, 1248(csp)
; CHECK-NEXT:    csc cnull, 1264(csp)
; CHECK-NEXT:    csc cnull, 1280(csp)
; CHECK-NEXT:    csc cnull, 1296(csp)
; CHECK-NEXT:    csc cnull, 1312(csp)
; CHECK-NEXT:    csc cnull, 1328(csp)
; CHECK-NEXT:    csc cnull, 1344(csp)
; CHECK-NEXT:    csc cnull, 1360(csp)
; CHECK-NEXT:    csc cnull, 1376(csp)
; CHECK-NEXT:    csc cnull, 1392(csp)
; CHECK-NEXT:    csc cnull, 1408(csp)
; CHECK-NEXT:    csc cnull, 1424(csp)
; CHECK-NEXT:    csc cnull, 1440(csp)
; CHECK-NEXT:    csc cnull, 1456(csp)
; CHECK-NEXT:    csc cnull, 1472(csp)
; CHECK-NEXT:    csc cnull, 1488(csp)
; CHECK-NEXT:    csc cnull, 1504(csp)
; CHECK-NEXT:    csc cnull, 1520(csp)
; CHECK-NEXT:    csc cnull, 1536(csp)
; CHECK-NEXT:    csc cnull, 1552(csp)
; CHECK-NEXT:    csc cnull, 1568(csp)
; CHECK-NEXT:    csc cnull, 1584(csp)
; CHECK-NEXT:    csc cnull, 1600(csp)
; CHECK-NEXT:    csc cnull, 1616(csp)
; CHECK-NEXT:    csc cnull, 1632(csp)
; CHECK-NEXT:    csc cnull, 1648(csp)
; CHECK-NEXT:    csc cnull, 1664(csp)
; CHECK-NEXT:    csc cnull, 1680(csp)
; CHECK-NEXT:    csc cnull, 1696(csp)
; CHECK-NEXT:    csc cnull, 1712(csp)
; CHECK-NEXT:    csc cnull, 1728(csp)
; CHECK-NEXT:    csc cnull, 1744(csp)
; CHECK-NEXT:    csc cnull, 1760(csp)
; CHECK-NEXT:    csc cnull, 1776(csp)
; CHECK-NEXT:    csc cnull, 1792(csp)
; CHECK-NEXT:    csc cnull, 1808(csp)
; CHECK-NEXT:    csc cnull, 1824(csp)
; CHECK-NEXT:    csc cnull, 1840(csp)
; CHECK-NEXT:    csc cnull, 1856(csp)
; CHECK-NEXT:    csc cnull, 1872(csp)
; CHECK-NEXT:    csc cnull, 1888(csp)
; CHECK-NEXT:    csc cnull, 1904(csp)
; CHECK-NEXT:    csc cnull, 1920(csp)
; CHECK-NEXT:    csc cnull, 1936(csp)
; CHECK-NEXT:    csc cnull, 1952(csp)
; CHECK-NEXT:    csc cnull, 1968(csp)
; CHECK-NEXT:    csc cnull, 1984(csp)
; CHECK-NEXT:    csc cnull, 2000(csp)
; CHECK-NEXT:    csc cnull, 2016(csp)
; CHECK-NEXT:    cincoffset csp, csp, 2032
; CHECK-NEXT:    cret
entry:
  %obj1 = alloca i128, align 16, addrspace(200)
  %obj2 = alloca %struct.too.large, align 1, addrspace(200)
  call i32 @use_i128(i128 addrspace(200)* %obj1)
  call i32 @use_too_large(%struct.too.large addrspace(200)* %obj2)
  ret void
}
